server:
  port: 8087
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

code-map:
  cmdline-mode: false
  service-path: /api
  es:
    hosts: 127.0.0.1:9300
    cluster-name: docker-cluster
